# Generated by Django 5.2.6 on 2026-07-28 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM being charged for', max_length=7)),
                ('issued_at', models.DateField()),
                ('due_on', models.DateField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(help_text='BDT')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='unpaid', max_length=8)),
            ],
            options={
                'db_table': 'bill',
                'ordering': ['-period', 'household_id'],
            },
        ),
        migrations.CreateModel(
            name='BillingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7, unique=True)),
                ('issued_on', models.DateField()),
                ('bill_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_run',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7)),
                ('amount', models.PositiveIntegerField(help_text='BDT handed in')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ref', models.CharField(blank=True, help_text='Deposit slip reference', max_length=32)),
            ],
            options={
                'db_table': 'deposit',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(help_text='BDT')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='bKash/bank transaction id', max_length=64)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-at'],
            },
        ),
    ]
