# Generated by Django 5.2.6 on 2026-07-28 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('fieldops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='customers.household'),
        ),
        migrations.AddField(
            model_name='bill',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.paymentmode'),
        ),
        migrations.AddField(
            model_name='bill',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='catalog.ward'),
        ),
        migrations.AddField(
            model_name='billingrun',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.billingrun'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='fieldops.collector'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.paymentmode'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collector',
            field=models.ForeignKey(blank=True, help_text='Who actually took the money', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fieldops.collector'),
        ),
        migrations.AddField(
            model_name='payment',
            name='deposit',
            field=models.ForeignKey(blank=True, help_text='Set once this cash has been handed in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.deposit'),
        ),
        migrations.AddField(
            model_name='payment',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.household'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.paymentmode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['period', 'status'], name='bill_period_a7e6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['household', '-period'], name='bill_househo_8eb1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['ward', 'period'], name='bill_ward_id_339b84_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('household', 'period'), name='bill_one_per_household_per_period'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['collector', 'period'], name='deposit_collect_0f7ec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.UniqueConstraint(fields=('collector', 'period', 'method'), name='deposit_unique_per_method'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['household', '-at'], name='payment_househo_239402_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['collector', '-at'], name='payment_collect_de0ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill'], name='payment_bill_id_125237_idx'),
        ),
    ]
