# Generated by Django 5.2.6 on 2026-08-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_backfill_single_agency'),
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='agencies.agency'),
        ),
    ]
