# Generated by Django 5.2.6 on 2026-08-09 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_backfill_stamped_agency'),
        ('billing', '0003_payment_agency'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='agencies.agency'),
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM being settled', max_length=7)),
                ('amount', models.PositiveIntegerField(help_text='BDT remitted')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ref', models.CharField(blank=True, help_text='Bank transfer / cheque / challan number', max_length=64)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='agencies.agency')),
                ('method', models.ForeignKey(help_text='How the agency paid KCC — bank transfer, cheque, cash', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.paymentmode')),
                ('received_by', models.ForeignKey(blank=True, help_text='The KCC officer who accepted it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remittance',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['agency', 'period'], name='remittance_agency_period_idx')],
            },
        ),
    ]
