# Generated by Django 5.2.6 on 2026-07-28 07:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialCustomer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('profession', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('blood_group', models.CharField(blank=True, max_length=4)),
                ('members', models.PositiveSmallIntegerField(default=0)),
                ('members_under5', models.PositiveSmallIntegerField(default=0)),
                ('members_female', models.PositiveSmallIntegerField(default=0)),
                ('floor', models.CharField(blank=True, max_length=32)),
                ('holding', models.CharField(help_text='Holding number, e.g. 142/B', max_length=24)),
                ('head', models.CharField(help_text='Head of household / contact name', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy', models.PositiveSmallIntegerField(blank=True, help_text='GPS accuracy in metres', null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('placed_by_hand', models.BooleanField(default=False, help_text='Pin dropped manually rather than captured from GPS')),
                ('surveyed_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'potential_customer',
                'ordering': ['-surveyed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('profession', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('blood_group', models.CharField(blank=True, max_length=4)),
                ('members', models.PositiveSmallIntegerField(default=0)),
                ('members_under5', models.PositiveSmallIntegerField(default=0)),
                ('members_female', models.PositiveSmallIntegerField(default=0)),
                ('floor', models.CharField(blank=True, max_length=32)),
                ('holding', models.CharField(help_text='Holding number, e.g. 142/B', max_length=24)),
                ('head', models.CharField(help_text='Head of household / contact name', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy', models.PositiveSmallIntegerField(blank=True, help_text='GPS accuracy in metres', null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('placed_by_hand', models.BooleanField(default=False, help_text='Pin dropped manually rather than captured from GPS')),
                ('qr', models.CharField(blank=True, help_text='QR tag printed on the bin sticker, e.g. SS-9F3A21', max_length=24, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('charge', models.PositiveIntegerField(default=0)),
                ('payment_day', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('dues', models.IntegerField(default=0)),
                ('converted_from', models.CharField(blank=True, help_text='PotentialCustomer id, if converted', max_length=32)),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.customertype')),
                ('holding_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.holdingtype')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.paymentmode')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.road')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.storagetype')),
                ('suitable_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.suitabletime')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='households', to='catalog.tier')),
            ],
            options={
                'db_table': 'household',
                'ordering': ['ward_id', 'road_id', 'holding'],
            },
        ),
    ]
