# Generated by Django 5.2.6 on 2026-07-28 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('fieldops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fieldops.collector'),
        ),
        migrations.AddField(
            model_name='household',
            name='verified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='household',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.ward'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='converted_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_survey', to='customers.household'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='current_practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.currentpractice'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.customertype'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='est_tier',
            field=models.ForeignKey(help_text='Tier this holding would fall into once signed up', on_delete=django.db.models.deletion.PROTECT, related_name='potential_customers', to='catalog.tier'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='holding_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.holdingtype'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.potentialreason'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.road'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.storagetype'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='suitable_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.suitabletime'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fieldops.collector'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='time_gap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.timegap'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fieldops.collector'),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='verified_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='potentialcustomer',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.ward'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['ward', 'status'], name='household_ward_id_12090e_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['verified'], name='household_verifie_cfaa5f_idx'),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['qr'], name='household_qr_cef95b_idx'),
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.UniqueConstraint(fields=('ward', 'road', 'holding'), name='household_unique_address'),
        ),
        migrations.AddIndex(
            model_name='potentialcustomer',
            index=models.Index(fields=['ward'], name='potential_c_ward_id_1ead53_idx'),
        ),
        migrations.AddIndex(
            model_name='potentialcustomer',
            index=models.Index(fields=['converted_at'], name='potential_c_convert_7cc27d_idx'),
        ),
    ]
