# Generated by Django 5.2.6 on 2026-08-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('customers', '0006_location_moves_to_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='agencies.agency'),
        ),
    ]
