# Generated by Django 5.2.6 on 2026-07-28 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('missed_collection', 'Missed collection'), ('overflow', 'Bin overflow'), ('billing_dispute', 'Billing dispute'), ('staff_behaviour', 'Staff behaviour'), ('other', 'Other')], max_length=24)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('app', 'App'), ('phone', 'Phone call'), ('counter', 'Service counter')], default='app', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=12)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('opened', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('sla', models.PositiveSmallIntegerField(help_text='Budget in hours')),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'complaint',
                'ordering': ['-opened'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('in_progress', 'Work started'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reassigned', 'Reassigned'), ('priority', 'Priority changed'), ('note', 'Note added'), ('reopened', 'Reopened')], max_length=16)),
                ('actor', models.CharField(default='System', max_length=120)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'complaint activity',
                'db_table': 'complaint_activity',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='complaints/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'complaint_photo',
                'ordering': ['created_at'],
            },
        ),
    ]
