# Generated by Django 5.2.6 on 2026-07-28 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('complaints', '0001_initial'),
        ('customers', '0001_initial'),
        ('fieldops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='fieldops.collector'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='customers.household'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='catalog.ward'),
        ),
        migrations.AddField(
            model_name='complaintactivity',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintactivity',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaintphoto',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaintphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-opened'], name='complaint_status_ced4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['ward', 'status'], name='complaint_ward_id_bcc918_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned', 'status'], name='complaint_assigne_8cf638_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['household'], name='complaint_househo_da2545_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintactivity',
            index=models.Index(fields=['complaint', 'at'], name='complaint_a_complai_e8fe91_idx'),
        ),
    ]
