# Generated by Django 5.2.6 on 2026-07-28 07:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fieldops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=48, unique=True)),
                ('type', models.CharField(choices=[('compactor', 'Compactor'), ('pickup', 'Pickup'), ('rickshaw-van', 'Rickshaw van'), ('tricycle', 'Tricycle')], max_length=16)),
                ('capacity', models.PositiveIntegerField(help_text='Payload capacity in kg')),
                ('fuel', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('electric', 'Electric')], max_length=10)),
                ('ownership', models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased')], default='owned', max_length=8)),
                ('gps', models.CharField(blank=True, help_text='Tracker device id', max_length=24)),
                ('odometer', models.PositiveIntegerField(default=0, help_text='Kilometres')),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_maintenance', 'In maintenance'), ('idle', 'Idle'), ('retired', 'Retired')], default='active', max_length=16)),
                ('fitness_exp', models.DateField(blank=True, null=True)),
                ('tax_exp', models.DateField(blank=True, null=True)),
                ('insurance_exp', models.DateField(blank=True, null=True)),
                ('permit_exp', models.DateField(blank=True, null=True)),
                ('next_service_km', models.PositiveIntegerField(blank=True, null=True)),
                ('kmpl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vans', to='fieldops.collector')),
            ],
            options={
                'db_table': 'van',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled')], max_length=12)),
                ('reason', models.CharField(max_length=200)),
                ('odometer', models.PositiveIntegerField()),
                ('opened', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('downtime', models.DecimalField(decimal_places=2, default=0, help_text='Hours out of service', max_digits=7)),
                ('cost', models.PositiveIntegerField(default=0, help_text='BDT')),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='fleet.van')),
            ],
            options={
                'db_table': 'maintenance',
                'ordering': ['-opened'],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cost', models.PositiveIntegerField(help_text='BDT')),
                ('odometer', models.PositiveIntegerField()),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kmpl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fieldops.collector')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.van')),
            ],
            options={
                'db_table': 'fuel_log',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='km/h', max_digits=5, null=True)),
                ('heading', models.PositiveSmallIntegerField(blank=True, help_text='Degrees', null=True)),
                ('accuracy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ignition', models.BooleanField(default=True)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fieldops.collector')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='fleet.van')),
            ],
            options={
                'db_table': 'vehicle_position',
                'ordering': ['-at'],
                'get_latest_by': 'at',
            },
        ),
        migrations.AddIndex(
            model_name='van',
            index=models.Index(fields=['status'], name='van_status_29b295_idx'),
        ),
        migrations.AddIndex(
            model_name='van',
            index=models.Index(fields=['driver'], name='van_driver__25e454_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['van', '-opened'], name='maintenance_van_id_4f2213_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['closed'], name='maintenance_closed_36975d_idx'),
        ),
        migrations.AddIndex(
            model_name='fuellog',
            index=models.Index(fields=['van', '-at'], name='fuel_log_van_id_f7755c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleposition',
            index=models.Index(fields=['van', '-at'], name='vehicle_pos_van_id_306176_idx'),
        ),
    ]
