# Generated by Django 5.2.6 on 2026-07-28 07:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('dsp_id', models.CharField(help_text='e.g. DSP-0042', max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('on_route', 'On route'), ('idle', 'Idle'), ('off_route', 'Off route')], default='idle', max_length=12)),
                ('attendance', models.CharField(choices=[('checked_in', 'Checked in'), ('absent', 'Absent')], default='checked_in', max_length=12)),
                ('license', models.CharField(blank=True, max_length=32)),
                ('license_exp', models.DateField(blank=True, null=True)),
                ('joined', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('on_time', models.PositiveSmallIntegerField(default=0, help_text='On-time completion %', validators=[django.core.validators.MaxValueValidator(100)])),
                ('coverage', models.PositiveSmallIntegerField(default=0, help_text='Stop coverage %', validators=[django.core.validators.MaxValueValidator(100)])),
                ('metrics_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ward', models.ForeignKey(help_text="Home ward. Exposed as 'zone' by the API for backwards compatibility.", on_delete=django.db.models.deletion.PROTECT, related_name='collectors', to='catalog.ward')),
            ],
            options={
                'db_table': 'collector',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fieldops.collector')),
            ],
            options={
                'db_table': 'assignment',
                'ordering': ['collector_id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Usually the road name', max_length=120)),
                ('window_start', models.TimeField(default='06:00')),
                ('window_end', models.TimeField(default='09:30')),
                ('active', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='catalog.ward')),
            ],
            options={
                'db_table': 'route',
                'ordering': ['ward_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_links', to='fieldops.assignment')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_links', to='fieldops.route')),
            ],
            options={
                'db_table': 'assignment_route',
                'ordering': ['assignment_id', 'seq'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='routes',
            field=models.ManyToManyField(related_name='assignments', through='fieldops.AssignmentRoute', to='fieldops.route'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField()),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_stop', to='customers.household')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='fieldops.route')),
            ],
            options={
                'db_table': 'route_stop',
                'ordering': ['route_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('qr', models.CharField(blank=True, help_text='Tag as scanned, kept for audit even if it changes', max_length=24)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('skipped', 'Skipped')], max_length=10)),
                ('at', models.DateTimeField(db_index=True)),
                ('served_on', models.DateField(db_index=True, help_text='Local date of `at`; one visit per household per day')),
                ('accuracy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source', models.CharField(blank=True, choices=[('scan', 'QR scan'), ('manual', 'Manual entry')], max_length=8)),
                ('reason', models.CharField(blank=True, choices=[('noOne', 'No one home'), ('noWaste', 'No waste to collect'), ('locked', 'Premises locked'), ('access', 'Could not access'), ('refused', 'Householder refused')], help_text='Required when skipped', max_length=12)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visits/%Y/%m/')),
                ('synced', models.BooleanField(default=True)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='fieldops.collector')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='customers.household')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='fieldops.route')),
            ],
            options={
                'db_table': 'visit',
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='collector',
            index=models.Index(fields=['ward', 'status'], name='collector_ward_id_4990a2_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['ward', 'active'], name='route_ward_id_476613_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentroute',
            constraint=models.UniqueConstraint(fields=('assignment', 'route'), name='assignment_route_unique'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('collector',), name='assignment_one_active_per_collector'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'seq'), name='route_stop_unique_seq'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['household', '-served_on'], name='visit_househo_87cd87_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['collector', '-served_on'], name='visit_collect_bb879a_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['served_on', 'status'], name='visit_served__fa4753_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['synced'], name='visit_synced_a4c95c_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('household', 'served_on'), name='visit_one_per_household_per_day'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'collected'), models.Q(('reason', ''), _negated=True), _connector='OR'), name='visit_skip_needs_reason'),
        ),
    ]
