# Generated by Django 5.2.6 on 2026-07-28 08:08

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('fieldops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routestop',
            name='route_stop_unique_seq',
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('route', 'seq'), name='route_stop_unique_seq'),
        ),
    ]
