# Generated by Django 5.2.6 on 2026-08-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('fieldops', '0003_visit_van'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collectors', to='agencies.agency'),
        ),
    ]
