# Generated by Django 5.2.6 on 2026-08-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_backfill_deposit_agency'),
        ('fieldops', '0005_visit_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='agencies.agency'),
        ),
    ]
