# Generated by Django 5.2.6 on 2026-07-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPractice',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=96)),
                ('label', models.CharField(max_length=96)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'current_practice',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=96)),
                ('label', models.CharField(max_length=96)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer_type',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoldingType',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=96)),
                ('label', models.CharField(max_length=96)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'holding_type',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=96)),
                ('label', models.CharField(max_length=96)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_mode',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PotentialReason',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=96)),
                ('label', models.CharField(max_length=96)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'potential_reason',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=96)),
                ('label', models.CharField(max_length=96)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'storage_type',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuitableTime',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=96)),
                ('label', models.CharField(max_length=96)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'suitable_time',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=96)),
                ('label', models.CharField(max_length=96)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('charge', models.PositiveIntegerField(help_text='Standard monthly charge, BDT')),
            ],
            options={
                'db_table': 'tier',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeGap',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=96)),
                ('label', models.CharField(max_length=96)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'time_gap',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=96)),
                ('name', models.CharField(max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'zone',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=96)),
                ('name', models.CharField(max_length=96)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='catalog.zone')),
            ],
            options={
                'db_table': 'ward',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='catalog.ward')),
            ],
            options={
                'db_table': 'road',
                'ordering': ['ward_id', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('ward', 'name'), name='road_unique_per_ward')],
            },
        ),
    ]
