# Generated by Django 5.2.6 on 2026-08-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.CharField(help_text='e.g. W-22-A', max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Block-A', max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='catalog.ward')),
            ],
            options={
                'db_table': 'block',
                'ordering': ['ward_id', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('ward', 'name'), name='block_unique_per_ward')],
            },
        ),
    ]
