# Generated by Django 5.2.6 on 2026-08-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('fieldops', '0003_visit_van'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('short_code', models.CharField(help_text="Short label for reports and exports, e.g. 'PCM'", max_length=12, unique=True)),
                ('agency_type', models.CharField(choices=[('private', 'Private company'), ('ngo', 'NGO'), ('cbo', 'Community-based organisation'), ('cooperative', 'Cooperative')], default='private', max_length=12)),
                ('trade_licence_no', models.CharField(blank=True, max_length=40)),
                ('registration_no', models.CharField(blank=True, help_text='NGO/society/cooperative registration, if any', max_length=40)),
                ('tin', models.CharField(blank=True, max_length=20, verbose_name='TIN')),
                ('bin', models.CharField(blank=True, max_length=20, verbose_name='BIN')),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contract_no', models.CharField(blank=True, max_length=40)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Contract expired'), ('terminated', 'Terminated')], default='active', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('service_wards', models.ManyToManyField(blank=True, related_name='agencies', to='catalog.ward')),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'db_table': 'agency',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectorEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, help_text="Null while this is the collector's current agency", null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='agencies.agency')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='fieldops.collector')),
            ],
            options={
                'db_table': 'collector_employment',
                'ordering': ['collector_id', '-from_date'],
            },
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['status'], name='agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectoremployment',
            index=models.Index(fields=['collector', '-from_date'], name='employment_collector_idx'),
        ),
        migrations.AddIndex(
            model_name='collectoremployment',
            index=models.Index(fields=['agency'], name='employment_agency_idx'),
        ),
        migrations.AddConstraint(
            model_name='collectoremployment',
            constraint=models.UniqueConstraint(condition=models.Q(('to_date__isnull', True)), fields=('collector',), name='employment_one_current_per_collector'),
        ),
        migrations.AddConstraint(
            model_name='collectoremployment',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__isnull', True), ('to_date__gte', models.F('from_date')), _connector='OR'), name='employment_dates_ordered'),
        ),
    ]
