// CSV / Excel / PDF (print) + preview helpers so export buttons actually work.
//
// Each entry point takes an optional { t } so the exported document is written
// in whichever language the operator is reading. Callers that omit it (tests,
// any non-React caller) fall back to English.

const EN = {
  'export.empty': 'Nothing to export.',
  'export.generatedBy': 'Generated by Smart Sweep SWMS',
  'export.print': '🖨 Print / Save as PDF',
  'export.popupBlocked': 'Please allow pop-ups to view / print the report.',
  'common.close': 'Close',
}
const tr = (opts, key) => opts?.t?.(key) || EN[key] || key

function escapeHtml(v) {
  if (v == null) return ''
  return String(v).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]))
}
function cellValue(col, row) {
  return typeof col.get === 'function' ? col.get(row) : row[col.key]
}
function resolveColumns(rows, columns) {
  if (columns) return columns
  // Union across all rows — taking only row 0's keys silently dropped any
  // column that first appears later in the set.
  const keys = []
  rows.forEach((r) => Object.keys(r || {}).forEach((k) => { if (!keys.includes(k)) keys.push(k) }))
  return keys.map((k) => ({ key: k, label: k }))
}
function download(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  // Revoking on the same tick as click() aborts the download in some browsers.
  setTimeout(() => URL.revokeObjectURL(url), 0)
}

// -------- CSV --------
// Excel and LibreOffice execute a cell that begins with = + - @ as a formula.
// Household names, addresses and complaint text are typed by field officers and
// citizens, so `=1+1` — or something aimed at whoever opens the export — must
// not be handed over live. Prefixing with an apostrophe is the standard
// neutralisation; quoting alone does NOT stop it.
const RISKY_LEAD = /^[=+\-@\t\r]/

function toCsvValue(v) {
  if (v == null) return ''
  let s = String(v)
  if (RISKY_LEAD.test(s)) s = `'${s}`
  // A bare \r matters on its own — an old-Mac line ending splits the row.
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}
export function downloadCSV(filename, rows, columns, opts) {
  if (!rows || !rows.length) { alert(tr(opts, 'export.empty')); return }
  const cols = resolveColumns(rows, columns)
  const header = cols.map((c) => toCsvValue(c.label)).join(',')
  const body = rows.map((r) => cols.map((c) => toCsvValue(cellValue(c, r))).join(',')).join('\n')
  download(new Blob(['﻿' + header + '\n' + body], { type: 'text/csv;charset=utf-8;' }),
    filename.endsWith('.csv') ? filename : `${filename}.csv`)
}

// -------- Excel (.xls via HTML table — opens natively in Excel, no deps) --------
export function downloadExcel(filename, rows, columns, title, opts) {
  if (!rows || !rows.length) { alert(tr(opts, 'export.empty')); return }
  const cols = resolveColumns(rows, columns)
  const head = cols.map((c) => `<th style="background:#0f7b4e;color:#fff;border:1px solid #0c6a43;padding:6px 10px;text-align:left">${escapeHtml(c.label)}</th>`).join('')
  const body = rows.map((r) => `<tr>${cols.map((c) => `<td style="border:1px solid #ccc;padding:5px 10px">${escapeHtml(cellValue(c, r))}</td>`).join('')}</tr>`).join('')
  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel">
    <head><meta charset="utf-8"><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet>
    <x:Name>${escapeHtml(title || 'Report')}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions>
    </x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head>
    <body>${title ? `<h3>${escapeHtml(title)}</h3>` : ''}<table>${`<thead><tr>${head}</tr></thead>`}<tbody>${body}</tbody></table></body></html>`
  download(new Blob(['﻿' + html], { type: 'application/vnd.ms-excel;charset=utf-8;' }),
    filename.endsWith('.xls') ? filename : `${filename}.xls`)
}

// -------- Shared report window (styled) --------
function reportShell(title, htmlBody, autoprint, opts) {
  const w = window.open('', '_blank', 'width=980,height=760')
  if (!w) { alert(tr(opts, 'export.popupBlocked')); return }
  w.document.write(`<!doctype html><html><head><title>${escapeHtml(title)}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400;600;700&display=swap">
    <style>
      body{font-family:'Segoe UI','Noto Sans Bengali',Arial,sans-serif;color:#16211c;padding:0;margin:0;background:#f3f4f6;}
      .bar{position:sticky;top:0;display:flex;gap:8px;justify-content:flex-end;padding:12px 24px;background:#fff;border-bottom:1px solid #e5e8e7;}
      .bar button{font:inherit;font-weight:600;font-size:13px;border:1px solid #0f7b4e;background:#0f7b4e;color:#fff;padding:8px 14px;border-radius:8px;cursor:pointer;}
      .bar button.ghost{background:#fff;color:#0f7b4e;}
      .page{max-width:900px;margin:20px auto;background:#fff;padding:32px;border:1px solid #e5e8e7;border-radius:10px;}
      h1{font-size:20px;margin:0 0 4px;} .sub{color:#66766c;font-size:13px;margin-bottom:20px;}
      table{width:100%;border-collapse:collapse;font-size:12.5px;margin-top:10px;}
      th{text-align:left;background:#0f7b4e;color:#fff;padding:8px 10px;font-size:11px;text-transform:uppercase;}
      td{padding:7px 10px;border-bottom:1px solid #e5e8e7;}
      tr:nth-child(even){background:#f6f8f7;}
      .foot{margin-top:24px;color:#8a968f;font-size:11px;}
      @media print{.bar{display:none;} body{background:#fff;} .page{border:none;margin:0;max-width:none;}}
    </style></head><body>
    <div class="bar">
      <button class="ghost" onclick="window.close()">${escapeHtml(tr(opts, 'common.close'))}</button>
      <button onclick="window.print()">${escapeHtml(tr(opts, 'export.print'))}</button>
    </div>
    <div class="page">${htmlBody}
      <div class="foot">${escapeHtml(tr(opts, 'export.generatedBy'))} · ${new Date().toLocaleString()}</div>
    </div>
    ${autoprint ? '<script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script>' : ''}
    </body></html>`)
  w.document.close()
}

// Open a viewable report (with a Print/Save-as-PDF button, no auto-print).
export function viewReport(title, htmlBody, opts) { reportShell(title, htmlBody, false, opts) }
// Open and immediately trigger the print dialog (Save as PDF).
export function printReport(title, htmlBody, opts) { reportShell(title, htmlBody, true, opts) }

export function tableToHTML(title, subtitle, columns, rows) {
  const head = columns.map((c) => `<th>${escapeHtml(c.label)}</th>`).join('')
  const body = rows.map((r) => `<tr>${columns.map((c) => `<td>${escapeHtml(cellValue(c, r))}</td>`).join('')}</tr>`).join('')
  return `<h1>${escapeHtml(title)}</h1><div class="sub">${escapeHtml(subtitle || '')}</div>
    <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`
}
