// CSV / Excel / PDF (print) + preview helpers so export buttons actually work.

function escapeHtml(v) {
  if (v == null) return ''
  return String(v).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))
}
function cellValue(col, row) {
  return typeof col.get === 'function' ? col.get(row) : row[col.key]
}
function resolveColumns(rows, columns) {
  return columns || Object.keys(rows[0]).map((k) => ({ key: k, label: k }))
}
function download(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

// -------- CSV --------
function toCsvValue(v) {
  if (v == null) return ''
  const s = String(v)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}
export function downloadCSV(filename, rows, columns) {
  if (!rows || !rows.length) { alert('Nothing to export.'); return }
  const cols = resolveColumns(rows, columns)
  const header = cols.map((c) => toCsvValue(c.label)).join(',')
  const body = rows.map((r) => cols.map((c) => toCsvValue(cellValue(c, r))).join(',')).join('\n')
  download(new Blob(['﻿' + header + '\n' + body], { type: 'text/csv;charset=utf-8;' }),
    filename.endsWith('.csv') ? filename : `${filename}.csv`)
}

// -------- Excel (.xls via HTML table — opens natively in Excel, no deps) --------
export function downloadExcel(filename, rows, columns, title) {
  if (!rows || !rows.length) { alert('Nothing to export.'); return }
  const cols = resolveColumns(rows, columns)
  const head = cols.map((c) => `<th style="background:#0f7b4e;color:#fff;border:1px solid #0c6a43;padding:6px 10px;text-align:left">${escapeHtml(c.label)}</th>`).join('')
  const body = rows.map((r) => `<tr>${cols.map((c) => `<td style="border:1px solid #ccc;padding:5px 10px">${escapeHtml(cellValue(c, r))}</td>`).join('')}</tr>`).join('')
  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel">
    <head><meta charset="utf-8"><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet>
    <x:Name>${escapeHtml(title || 'Report')}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions>
    </x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head>
    <body>${title ? `<h3>${escapeHtml(title)}</h3>` : ''}<table>${`<thead><tr>${head}</tr></thead>`}<tbody>${body}</tbody></table></body></html>`
  download(new Blob(['﻿' + html], { type: 'application/vnd.ms-excel;charset=utf-8;' }),
    filename.endsWith('.xls') ? filename : `${filename}.xls`)
}

// -------- Shared report window (styled) --------
function reportShell(title, htmlBody, autoprint) {
  const w = window.open('', '_blank', 'width=980,height=760')
  if (!w) { alert('Please allow pop-ups to view / print the report.'); return }
  w.document.write(`<!doctype html><html><head><title>${escapeHtml(title)}</title>
    <style>
      body{font-family:'Segoe UI',Arial,sans-serif;color:#16211c;padding:0;margin:0;background:#f3f4f6;}
      .bar{position:sticky;top:0;display:flex;gap:8px;justify-content:flex-end;padding:12px 24px;background:#fff;border-bottom:1px solid #e5e8e7;}
      .bar button{font:inherit;font-weight:600;font-size:13px;border:1px solid #0f7b4e;background:#0f7b4e;color:#fff;padding:8px 14px;border-radius:8px;cursor:pointer;}
      .bar button.ghost{background:#fff;color:#0f7b4e;}
      .page{max-width:900px;margin:20px auto;background:#fff;padding:32px;border:1px solid #e5e8e7;border-radius:10px;}
      h1{font-size:20px;margin:0 0 4px;} .sub{color:#66766c;font-size:13px;margin-bottom:20px;}
      table{width:100%;border-collapse:collapse;font-size:12.5px;margin-top:10px;}
      th{text-align:left;background:#0f7b4e;color:#fff;padding:8px 10px;font-size:11px;text-transform:uppercase;}
      td{padding:7px 10px;border-bottom:1px solid #e5e8e7;}
      tr:nth-child(even){background:#f6f8f7;}
      .foot{margin-top:24px;color:#8a968f;font-size:11px;}
      @media print{.bar{display:none;} body{background:#fff;} .page{border:none;margin:0;max-width:none;}}
    </style></head><body>
    <div class="bar">
      <button class="ghost" onclick="window.close()">Close</button>
      <button onclick="window.print()">🖨 Print / Save as PDF</button>
    </div>
    <div class="page">${htmlBody}
      <div class="foot">Generated by Smart Sweep SWMS · ${new Date().toLocaleString()}</div>
    </div>
    ${autoprint ? '<script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script>' : ''}
    </body></html>`)
  w.document.close()
}

// Open a viewable report (with a Print/Save-as-PDF button, no auto-print).
export function viewReport(title, htmlBody) { reportShell(title, htmlBody, false) }
// Open and immediately trigger the print dialog (Save as PDF).
export function printReport(title, htmlBody) { reportShell(title, htmlBody, true) }

export function tableToHTML(title, subtitle, columns, rows) {
  const head = columns.map((c) => `<th>${escapeHtml(c.label)}</th>`).join('')
  const body = rows.map((r) => `<tr>${columns.map((c) => `<td>${escapeHtml(cellValue(c, r))}</td>`).join('')}</tr>`).join('')
  return `<h1>${escapeHtml(title)}</h1><div class="sub">${escapeHtml(subtitle || '')}</div>
    <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`
}
