# Generated by Django 5.2.6 on 2026-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdSequence',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('last_value', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'id sequence',
                'db_table': 'id_sequence',
            },
        ),
    ]
