# Generated by Django 5.2.6 on 2026-07-28 07:51

import swms.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('collector', 'Collector'), ('supervisor', 'Supervisor'), ('agency_admin', 'Agency Admin'), ('kcc_viewer', 'KCC Viewer')], default='collector', max_length=20)),
                ('scope_kind', models.CharField(choices=[('ward', 'Ward'), ('zone', 'Zone'), ('agency', 'All zones'), ('city', 'City-wide')], default='ward', max_length=10)),
                ('scope_zone', models.CharField(blank=True, help_text='Zone id, e.g. Z-03', max_length=8)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('nid', models.CharField(blank=True, max_length=30, verbose_name='National ID')),
                ('blood_group', models.CharField(blank=True, max_length=4)),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('pin_set_at', models.DateTimeField(blank=True, null=True)),
                ('pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('pin_locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_account',
                'ordering': ['name'],
            },
            managers=[
                ('objects', swms.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_otp_code',
                'ordering': ['-created_at'],
            },
        ),
    ]
