# Generated by Django 5.2.6 on 2026-08-09 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0005_backfill_route_agency'),
        ('catalog', '0002_block'),
        ('customers', '0007_holding_agency'),
        ('fieldops', '0006_route_agency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('number', models.CharField(blank=True, help_text="As printed, e.g. '29'", max_length=8)),
                ('section', models.CharField(blank=True, max_length=60)),
                ('kind', models.CharField(choices=[('single', 'One choice'), ('multi', 'Several choices'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('note', 'Section heading / instruction')], max_length=8)),
                ('text', models.CharField(max_length=300)),
                ('text_bn', models.CharField(blank=True, max_length=300)),
                ('hint', models.CharField(blank=True, max_length=300)),
                ('hint_bn', models.CharField(blank=True, max_length=300)),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('maps_to', models.CharField(blank=True, max_length=32)),
                ('options_source', models.CharField(choices=[('static', 'The options listed on the form'), ('ward', 'Wards, from the catalog'), ('block', 'Blocks of the chosen ward'), ('collector', 'Collectors on record')], default='static', max_length=12)),
            ],
            options={
                'db_table': 'survey_question',
                'ordering': ['form_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48)),
                ('label', models.CharField(max_length=200)),
                ('label_bn', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_other', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question')),
            ],
            options={
                'db_table': 'survey_question_option',
                'ordering': ['question_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('answered', 'Has any answer'), ('equals', 'Is one of these options'), ('not_equals', 'Is none of these options')], default='equals', max_length=12)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='surveys.question')),
                ('options', models.ManyToManyField(blank=True, related_name='rules', to='surveys.questionoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='surveys.question')),
            ],
            options={
                'db_table': 'survey_question_rule',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('surveyor_name', models.CharField(blank=True, help_text='As given on the form, when the surveyor is not a collector on record', max_length=120)),
                ('surveyed_on', models.DateField(db_index=True)),
                ('road_name', models.CharField(blank=True, max_length=160)),
                ('holding_no', models.CharField(blank=True, db_index=True, max_length=24)),
                ('respondent_name', models.CharField(blank=True, max_length=120)),
                ('respondent_phone', models.CharField(blank=True, max_length=20)),
                ('premises_type', models.CharField(blank=True, max_length=40)),
                ('household_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daily_waste_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('gives_to_van', models.BooleanField(blank=True, null=True)),
                ('monthly_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('willing_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('accuracy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('converted', 'Converted to a holding'), ('rejected', 'Rejected')], default='submitted', max_length=10)),
                ('synced', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='agencies.agency')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='catalog.block')),
                ('converted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_taken', to='customers.holding')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='fieldops.collector')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='catalog.ward')),
            ],
            options={
                'db_table': 'survey',
                'ordering': ['-surveyed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.question')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='surveys.questionoption')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.survey')),
            ],
            options={
                'db_table': 'survey_answer',
                'ordering': ['survey_id', 'question__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Stable key, e.g. 'd2d-household'", max_length=40)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('title_bn', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survey_form',
                'ordering': ['code', '-version'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='survey_form_unique_version')],
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='surveys.surveyform'),
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveyform'),
        ),
        migrations.CreateModel(
            name='SurveyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='surveys/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='surveys.survey')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_photo',
                'ordering': ['survey_id', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'code'), name='option_unique_per_question'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['survey', 'question'], name='answer_survey_q_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('survey', 'question', 'option'), name='answer_unique_choice'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['form', '-surveyed_on'], name='survey_form_date_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['ward', '-surveyed_on'], name='survey_ward_date_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status'], name='survey_status_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['form', 'sort_order'], name='question_form_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('form', 'code'), name='question_unique_code_per_form'),
        ),
    ]
