# Generated by Django 5.2.6 on 2026-08-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='owner_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
