# Generated by Django 5.2.6 on 2026-08-12 04:09

"""How much room a question's answer needs on screen.

Blank everywhere, including on v1, which is correct: blank means "infer it from
the kind", which is exactly what the client did before this column existed. Only
the handful of questions where that inference is wrong — a paragraph of
recommendation, a described premises — set it, and they set it in the
questionnaire module, not here.

Reversible: dropping it returns every question to the inferred width.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_district_survey_thana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='width',
            field=models.CharField(blank=True, choices=[('normal', 'A third of the row'), ('wide', 'Half the row'), ('full', 'The whole row')], help_text='Override the width the client would infer from the kind.', max_length=6),
        ),
    ]
