# Generated by Django 5.2.6 on 2026-09-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_survey_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default_value',
            field=models.CharField(blank=True, help_text="Prefilled for the surveyor; an option code, a date, 'today', or a literal.", max_length=120),
        ),
    ]
